---

# FIXME: it's not optimal, working as non-root should be the default
ansible_user: root

deployment_type: openshift-enterprise
openshift_deployment_type: openshift-enterprise
openshift_master_cluster_method: native
openshift_release: v3.11


# HTPASSWD Identity Provider
openshift_master_identity_providers:
 - 'name': 'htpasswd_auth'
   'login': 'true'
   'challenge': 'true'
   'kind': 'HTPasswdPasswordIdentityProvider'


#this will create an admin/admin user   
openshift_master_htpasswd_users:
  admin: $apr1$7aiANAYb$TOUYVUqnBqBlD5AQEIMYw1   

openshift_hosted_manage_router: true

openshift_hosted_manage_registry: true

openshift_docker_options: "--log-driver=json-file --log-opt max-size=50m --log-opt max-file=100"

os_sdn_network_plugin_name: 'redhat/openshift-ovs-networkpolicy'
#os_sdn_network_plugin_name: 'redhat/openshift-ovs-multitenant'
os_firewall_use_firewalld: true
osm_cluster_network_cidr: 10.1.0.0/16
  
openshift_enable_service_catalog: false
openshift_hosted_prometheus_deploy: false
openshift_cfme_install_app: false

# Registry URL & Credentials
# You can use your RHSM credentials or create service ones at the below URL:
# https://access.redhat.com/terms-based-registry/
oreg_url: 'registry.redhat.io/openshift3/ose-${component}:${version}'
oreg_auth_user: "{{ lookup('env', 'OREG_AUTH_USER') or lookup('env', 'RHSM_USER') }}"
oreg_auth_password: "{{ lookup('env', 'OREG_AUTH_PASSWORD' ) or lookup('env', 'RHSM_PASSWD') }}"

# remove the following or overwrite minimas with openshift_check_min_host_memory_gb
# or openshift_check_min_host_disk_gb (we assume a non-productive cluster on Libvirt):
openshift_disable_check: "disk_availability,memory_availability"
