---

- name: 'Install packages required for user creation in htpasswd'
  package:
    name: "{{ ((ansible_python_interpreter | default('somepython'))[-1] == '3') | ternary('python3-passlib','python-passlib') }}"
    state: installed

- name: "Create {{ create_users.num_users }} htpasswd users"
  htpasswd:
    path: "{{ create_users.passwd_file }}"
    name: "{{ create_users.prefix + '%02d' | format(item) }}"
    password: "{{ create_users.password }}"
    owner: root
    group: root
    mode: 0600
  loop: "{{ range(1, create_users.num_users + 1)|list }}"
  loop_control:
    label: "{{ create_users.prefix + '%02d' | format(item) }}"
