---
libvirt_name: "ocp_master.local"
libvirt_title: "OCP Master"
libvirt_description: "Master for OpenShift"
libvirt_memory: "2048"
libvirt_vcpus: "1"
libvirt_disk_size: "15"
libvirt_os_variant: "rhel7"
libvirt_iso: "~/Downloads/rhel-server-7.5-x86_64-dvd.iso"
libvirt_ksfile: "{{ inventory_dir }}/../files/ks/master.ks"
libvirt_http_host: '192.168.123.1'

infrahost: cloud-host.local
ansible_user: root
ansible_ssh_pass: redhat
